name: Build and Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ github.sha }}
          path: dist
          retention-days: 7
      - name: Webhook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: "https://picol.g.kuroco.app/direct/menu/github/"
          webhook_secret: "c8d46940eda0f5b27daeda1ade4a5e43"
          data: '{"domain":"demo.picol.app", "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'
